esphome:
  name: detect-change-example

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  js_include: "www.js"
  js_url: ""
button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
datetime:
  - platform: template
    id: my_datetime
    name: Pick a Datetime
    optimistic: yes
    initial_value: "2024-01-30"
    restore_value: true
    on_value:
      then:
        - logger.log: "datetime has changed!"