esphome:
  name: display-sntp-time-example

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  js_include: "www.js"
  js_url: ""

time:
  - platform: sntp
    id: my_time
    on_time:
      seconds: /1
      then:
        - datetime.set:
            id: my_datetime
            value: !lambda |-
              return id(my_time).now().strftime("%Y-%m-%d %H:%M:%S");

datetime:
  - platform: template
    id: my_datetime
    name: Pick a Datetime
    optimistic: yes